# Numpy Arrays

In [1]:
import numpy as np

## Basic Array Properties

In [2]:
a = np.arange(15).reshape(3, 5)
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [3]:
print("Shape of array =", a.shape)

Shape of array = (3, 5)


In [4]:
print("No. of dimensions of array =", a.ndim)

No. of dimensions of array = 2


In [5]:
print("Data type of array =", a.dtype)

Data type of array = int64


In [6]:
print("Size of each element of array in bytes =", a.itemsize)

Size of each element of array in bytes = 8


In [7]:
print("Type of the numpy array =", type(a))

Type of the numpy array = <class 'numpy.ndarray'>


## Array Creation

In [8]:
b = np.array([1, 2, 3])

print("Array =", b)
print("Array dtype =", b.dtype)

Array = [1 2 3]
Array dtype = int64


In [9]:
c = np.array([1.1, 2.52, 3.76])

print("Array =", c)
print("Array dtype =", c.dtype)

Array = [ 1.1   2.52  3.76]
Array dtype = float64


In [10]:
d = np.array([(1, 5.3), (6, 7)])

print("Array =")
print(d)
print("Array dtype =", d.dtype)

Array =
[[ 1.   5.3]
 [ 6.   7. ]]
Array dtype = float64


In [11]:
e = np.array([(1, 5.3), (6, 7)], dtype = complex)

print("Array =")
print(e)
print("Array dtype =", e.dtype)

Array =
[[ 1.0+0.j  5.3+0.j]
 [ 6.0+0.j  7.0+0.j]]
Array dtype = complex128


In [12]:
f = np.zeros((4, 6))

print("Array =")
print(f)
print("Array dtype =", f.dtype)

Array =
[[ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.]]
Array dtype = float64


In [13]:
g = np.ones((4, 6))

print("Array =")
print(g)
print("Array dtype =", g.dtype)

Array =
[[ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]
 [ 1.  1.  1.  1.  1.  1.]]
Array dtype = float64


In [14]:
h = np.linspace(4, 7, 9)

print("Array =", h)
print("Array dtype =", h.dtype)

Array = [ 4.     4.375  4.75   5.125  5.5    5.875  6.25   6.625  7.   ]
Array dtype = float64
